"""empty message

Revision ID: 253ea2fb155b
Revises: 3aaa4cb50fab
Create Date: 2019-03-10 08:49:03.719917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253ea2fb155b'
down_revision = '3aaa4cb50fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###
