"""empty message

Revision ID: 2f21893d61a4
Revises: 
Create Date: 2019-03-04 23:01:56.512697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f21893d61a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('account', sa.String(length=24), nullable=True))
    op.add_column('Users', sa.Column('nickname', sa.String(length=24), nullable=True))
    op.create_unique_constraint(None, 'Users', ['nickname'])
    op.create_unique_constraint(None, 'Users', ['account'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'nickname')
    op.drop_column('Users', 'account')
    # ### end Alembic commands ###
