"""empty message

Revision ID: 3aaa4cb50fab
Revises: 2f21893d61a4
Create Date: 2019-03-05 13:28:16.718744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3aaa4cb50fab'
down_revision = '2f21893d61a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
