"""empty message

Revision ID: 3af23fff85aa
Revises: ab49c357f376
Create Date: 2019-03-30 00:04:28.838900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af23fff85aa'
down_revision = 'ab49c357f376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Department', sa.Column('Name', sa.String(length=30), nullable=True))
    op.add_column('Users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Department', ['department_id'], ['ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'department_id')
    op.drop_column('Department', 'Name')
    # ### end Alembic commands ###
