"""empty message

Revision ID: 8870a89d2476
Revises: 3af23fff85aa
Create Date: 2019-04-06 15:48:10.780564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8870a89d2476'
down_revision = '3af23fff85aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Department', sa.Column('TestColumn', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Department', 'TestColumn')
    # ### end Alembic commands ###
