"""empty message

Revision ID: c8f47fa906ff
Revises: b2f26f5a4709
Create Date: 2019-03-10 08:54:44.941367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f47fa906ff'
down_revision = 'b2f26f5a4709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('Users', sa.Column('password', sa.String(length=100), nullable=True))
    op.add_column('Users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'phone')
    op.drop_column('Users', 'password')
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###
