"""empty message

Revision ID: f9c186e6d633
Revises: 8870a89d2476
Create Date: 2019-04-06 15:50:59.035313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9c186e6d633'
down_revision = '8870a89d2476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Department', 'TestColumn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Department', sa.Column('TestColumn', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
