"""empty message

Revision ID: fd5b9c0cd2d5
Revises: b97c9423f0e1
Create Date: 2019-03-14 22:48:43.924091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd5b9c0cd2d5'
down_revision = 'b97c9423f0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('CreateTime', sa.DateTime(), nullable=True))
    op.add_column('Comment', sa.Column('SysStatus', sa.SmallInteger(), nullable=True))
    op.add_column('Users', sa.Column('CreateTime', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('SysStatus', sa.SmallInteger(), nullable=True))
    op.drop_column('Users', 'cdate')
    op.drop_column('Users', 'sysstatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('sysstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('cdate', mysql.DATETIME(), nullable=True))
    op.drop_column('Users', 'SysStatus')
    op.drop_column('Users', 'CreateTime')
    op.drop_column('Comment', 'SysStatus')
    op.drop_column('Comment', 'CreateTime')
    # ### end Alembic commands ###
